#For full documentation of the parameters in this file, and a list of all the
#parameters available for DWAPlannerROS, please see
#http://www.ros.org/wiki/dwa_local_planner
EBandPlannerROS:
  max_vel_lin: 3
  min_vel_lin: -3.0
  max_vel_th: 2
  min_vel_th: 0.0

  min_in_place_vel_th: 0.0
  in_place_trans_vel: 0.0

  differential_drive: false

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.17

  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
